name: Convert Markdown to HTML

on:
  push:
    paths:
      - 'news-md/**/*.md'
      - '.github/workflows/convert-md-to-html.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install gray-matter marked

      - name: Convert .md to .html
        run: node tools/convert.js

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add news/*.html files-html.json
          git commit -m "auto: converted markdown to html"
          git push
