name: Generate files-html.json

on:
  push:
    paths:
      - 'news/*.html'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate files-html.json
        run: |
          echo "[" > news/files-html.json
          find news -maxdepth 1 -type f -name '*.html' \
            ! -name 'files-html.json' \
            -printf '  "%f",\n' | sort -r >> news/files-html.json
          sed -i '$ s/,$//' news/files-html.json
          echo "]" >> news/files-html.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add news/files-html.json
          git commit -m "Auto-generate files-html.json"
          git push
